groups:
  - name: hellov2.rules
    rules:
      - alert: HelloV2Down
        expr: up{job="hellov2"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "HelloV2 is down"
          description: "Prometheus cannot scrape /actuator/prometheus from HelloV2."

      - alert: HelloV2HighErrorRate
        expr: |
          (
            sum(rate(http_server_requests_seconds_count{job="hellov2",status=~"5.."}[1m]))
            /
            sum(rate(http_server_requests_seconds_count{job="hellov2"}[1m]))
          ) > 0.2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High 5xx rate in HelloV2"
          description: "More than 20% of HTTP requests are 5xx (1m window)."
#      - alert: AlwaysFiringTest
#        expr: vector(1)
#        for: 10s
#        labels:
#          severity: test
#        annotations:
#          summary: "Test alert"
#          description: "This alert is always firing (test)."